source 1_set_vars.sql

DELETE from datadictionary where instance=@instance and scope=@scope and entity=@entity;

INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','1','scqDate','Date of Evaluation','0-99','','1','scq','scq_date','1','date','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','2','scqName','Examiner','','','1','scq','scq_name','2','varchar','20','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','3','scq1','1. Is she/he now able to talk using short phrases or sentences? ','1=Yes, 0=No','','1','scq','scq1','3','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','4','scq2','2. Can you have a to and fro "conversation" with her/him that involves taking turns or building on what you have said?','1=Yes, 0=No','','1','scq','scq2','4','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','5','scq3','3. Has she/he ever used odd phrases or said the same thing over and over in almost exactly the same way (either phrases that she/he has heard other people use or ones that she/he has made up)?','1=Yes, 0=No','','1','scq','scq3','5','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','6','scq4','4. Has she/he ever used socially inappropriate questions or statements? For example. has she/he ever regularly asked personal questions or made personal comments at awkward times?','1=Yes, 0=No','','1','scq','scq4','6','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','7','scq5','5. Has she/he ever got her/his pronouns mixed up (e.g., saying you or she/he for I)?','1=Yes, 0=No','','1','scq','scq5','7','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','8','scq6','6. Has she/he ever used words that she/he seemed to have invented or made up her/himself; put things in odd, indirect ways; or used metaphorical ways of saying things {e.g., saying hot rain for steam)?','1=Yes, 0=No','','1','scq','scq6','8','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','9','scq7','7. Has she/he ever said the same thing over and over in exactly the same way or insisted that you say the same thing over and over again? ','1=Yes, 0=No','','1','scq','scq7','9','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','10','scq8','8. Has she/he ever had things that she/he seemed to have to do in a very particular way or order or rituals that she/he insisted that you go through?','1=Yes, 0=No','','1','scq','scq8','10','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','11','scq9','9. Has her/his facial expression usually seemed appropriate to the particular situation. as far as you could tell? ','1=Yes, 0=No','','1','scq','scq9','11','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','12','scq10',' 10. Has she/he ever used your hand like a tool or as if it were part of her/his own body (e.g., pointing with your finger, putting your hand on a doorknob to get you to open the door)?','1=Yes, 0=No','','1','scq','scq10','12','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','13','scq11','11. Has she/he ever had any interests that preoccupy her/him and might seem odd to other people (e.g., traffic lights, drainpipes, or timetables)? ','1=Yes, 0=No','','1','scq','scq11','13','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','14','scq12','12. Has she/he ever seemed to be more interested in parts of a toy or an object (e.g., spinning the wheels of a car), rather than using the object as it was intended?','1=Yes, 0=No','','1','scq','scq12','14','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','15','scq13','13. Has she/he ever had any special interests that were unusual in their intensity but otherwise appropriate for her/his age and peer group (e.g., trains, dinosaurs)? ','1=Yes, 0=No','','1','scq','scq13','15','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','16','scq14','14. Has she/he ever seemed to be unusually interested in the sight, feel, sound, taste. or smell of things or people? ','1=Yes, 0=No','','1','scq','scq14','16','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','17','scq15','15. Has she/he ever had any mannerisms or odd ways of moving her/his hands or fingers, such as flapping or moving her/his fingers in front of her/his eyes?','1=Yes, 0=No','','1','scq','scq15','17','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','18','scq16','16. Has she/he ever had any complicated movements of her/his whole body, such as spinning or repeatedly bouncing up and down?','1=Yes, 0=No','','1','scq','scq16','18','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','19','scq17','17. Has she/he ever injured her/himself deliberately, such as by biting her/his arm or banging her/his head?','1=Yes, 0=No','','1','scq','scq17','19','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','20','scq18','18. Has she/he ever had any objects {other than a soft toy or comfort blanket) that she/he had to carry around?','1=Yes, 0=No','','1','scq','scq18','20','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','21','scq19','19. Does she/he have any particular friends or a best friend?','1=Yes, 0=No','','1','scq','scq19','21','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','22','scq20','20. When she/he was 4 to 5, did she/he ever talk with you just to be friendly (rather than to get something)?','1=Yes, 0=No','','1','scq','scq20','22','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','23','scq21','21. When she/he was 4 to 5. did she/he ever spontaneously copy you (or other people) or what you were doing (such as vacuuming, gardening, or mending things)?','1=Yes, 0=No','','1','scq','scq21','23','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','24','scq22','22. When she/he was 4 to 5, did she/he ever spontaneously point at things around her/him just to show you things (not because she/he wanted them)?','1=Yes, 0=No','','1','scq','scq22','24','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','25','scq23','23. When she/he was 4 to 5, did she/he ever use gestures, other than pointing or pulling your hand, to let you know what she/he wanted?','1=Yes, 0=No','','1','scq','scq23','25','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','26','scq24','24. When she/he was 4 to 5, did she/he nod her/his head to mean yes?','1=Yes, 0=No','','1','scq','scq24','26','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','27','scq25','25. When she/he was 4 to 5, did she/he shake her/his head to mean no?','1=Yes, 0=No','','1','scq','scq25','27','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','28','scq26','26. When she/he was 4 to 5, did she/he usually look at you directly in the face when doing things with you or talking with you? ','1=Yes, 0=No','','1','scq','scq26','28','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','29','scq27','27. When she/he was 4 to 5, did she/he smile back if someone smiled at her/him?','1=Yes, 0=No','','1','scq','scq27','29','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','30','scq28','28. When she/he was 4 to 5, did she/he ever show you things that interested her/him to engage your attention?','1=Yes, 0=No','','1','scq','scq28','30','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','31','scq29','29. When she/he was 4 to 5. did she/he ever offer to share things other than food with you?','1=Yes, 0=No','','1','scq','scq29','31','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','32','scq30','30. When she/he was 4 to 5, did she/he ever seem to want you to join in her/his enjoyment of something? ','1=Yes, 0=No','','1','scq','scq30','32','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','33','scq31','31. When she/he was 4 to 5. did she/he ever try to comfort you if you were sad or hurt?','1=Yes, 0=No','','1','scq','scq31','33','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','34','scq32','32. When she/he was 4 to 5, when she/he wanted something or wanted help, did she/he look at you and use gestures with sounds or words to get your attention?','1=Yes, 0=No','','1','scq','scq32','34','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','35','scq33','33. When she/he was 4 to 5, did she/he show a normal range of facial expressions? ','1=Yes, 0=No','','1','scq','scq33','35','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','36','scq34','34. When she/he was 4 to 5, did she/he ever spontaneously join in and try to copy the actions in social games, such as The Mulberry Bush or London Bridge Is Falling Down?','1=Yes, 0=No','','1','scq','scq34','36','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','37','scq35','35. When she/he was 4 to 5, did she/he play any pretend or make-believe games?','1=Yes, 0=No','','1','scq','scq35','37','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','38','scq36','36. When she/he was 4 to 5, did she/he seem interested in other children of approximately the same age whom she/he did not know?','1=Yes, 0=No','','1','scq','scq36','38','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','39','scq37','37. When she/he was 4 to 5, did she/he respond positively when another child approached her/him?','1=Yes, 0=No','','1','scq','scq37','39','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','40','scq38','38. When she/he was 4 to 5, if you came into a room and started talking to her/him without calling her/his name, did she/he usually look up and pay attention to you?','1=Yes, 0=No','','1','scq','scq38','40','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','41','scq39','39. When she/he was 4 to 5, did she/he ever play imaginative games with another child in such a way that you could tell that they each understood what the other was pretending?','1=Yes, 0=No','','1','scq','scq39','41','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','42','scq40','40. When she/he was 4 to 5, did she/he play cooperatively in games that required joining in with a group of other children, such as hide-and-seek or ball games?','1=Yes, 0=No','','1','scq','scq40','42','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','43','scqSocial','Social Behavior Raw Score','','SCQ9 + SCQ19 + SCQ26 + SCQ27 + SCQ28 + SCQ29 + SCQ30 + SCQ31 + SCQ32 + SCQ33 + SCQ36 + SCQ37 + SCQ38 + SCQ39 + SCQ40','1','scq','scq_social','43','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','44','scqComm','Communication/Language Raw Score','','SCQ2 + SCQ3 + SCQ4 + SCQ5 + SCQ6 + SCQ20 + SCQ21 + SCQ22 + SCQ23 + SCQ24 + SCQ25 + SCQ34 + SCQ35','1','scq','scq_comm','44','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','45','scqPatterns','Stereotype Patterns Raw Score','','SCQ7 + SCQ8 + SCQ11 + SCQ12 + SCQ13 + SCQ14 + SCQ15 + SCQ16','1','scq','scq_patterns','45','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','app-pedi','scq','46','scqTotal','Total Raw Score','','SCQ1 + SCQ2 + SCQ3 + SCQ4 + SCQ5 + SCQ6 + SCQ7 + SCQ8 + SCQ9 + SCQ10 + SCQ11 + SCQ12 + SCQ13 + SCQ14 + SCQ15 + SCQ16 + SCQ17 + SCQ18 + SCQ19 + SCQ20 + SCQ21 + SCQ22 + SCQ23 + SCQ24 + SCQ25 + SCQ26 + SCQ27 + SCQ28 + SCQ29 + SCQ30 + SCQ31 + SCQ32 + SCQ33 + SCQ34 + SCQ35 + SCQ36 + SCQ37 + SCQ38 + SCQ39 + SCQ40','1','scq','scq_total','46','smallint','','37','null');
 

SELECT concat('use ', @db, ';');
SELECT '';
call util_createtable(@entity,@scope);
SELECT '';
call util_tablekeysadd(@entity,@scope);
SELECT '';
SELECT concat('INSERT IGNORE into instrument(instrname, tablename, formname, hasversion) values(\'', @instrname, '\',\'', @table, '\',\'LavaWebOnly\',0);');
