DELETE FROM viewproperty WHERE scope = 'crms-import';
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.import.projName','en','lava','crms-import',NULL,'import','projName',NULL,'i','range','Yes','Project',NULL,NULL,NULL,0,NULL,'context.projectList',NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.projName','en','lava','crms-import',NULL,'importLog','projName',NULL,'c','string',NULL,'Project',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.patientMustExist','en','lava','crms-import',NULL,'importDefinition','patientMustExist',NULL,'i','toggle',NULL,'Patient Must Exist',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Patient Must Exist','2014-04-28 16:11:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.projNameForContext','en','lava','crms-import',NULL,'importDefinition','projNameForContext',NULL,'i','range',NULL,'Project',NULL,NULL,NULL,0,NULL,'enrollmentStatus.patientProjects',NULL,NULL,'Project Context for Visit Data','2014-04-28 16:13:30');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitMustExist','en','lava','crms-import',NULL,'importDefinition','visitMustExist',NULL,'i','toggle',NULL,'Visit Must Exist',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Must Exist','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitTypeSupplied','en','lava','crms-import',NULL,'importDefinition','visitTypeSupplied',NULL,'i','toggle',NULL,'Visit Type Supplied in Data File',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Type Supplied in Data File','2014-04-28 16:20:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitType','en','lava','crms-import',NULL,'importDefinition','visitType',NULL,'i','range',NULL,'Visit Type',NULL,NULL,NULL,0,NULL,'visit.visitTypes',NULL,NULL,'Visit Type','2014-04-28 16:21:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitWithSupplied','en','lava','crms-import',NULL,'importDefinition','visitWithSupplied',NULL,'i','toggle',NULL,'Appt With Supplied in Data File',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Appt With Supplied in Data File','2014-04-28 16:25:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitWith','en','lava','crms-import',NULL,'importDefinition','visitWith',NULL,'i','suggest',NULL,'Appt With',NULL,NULL,NULL,0,NULL,'project.staffList',NULL,NULL,'Appointment With','2014-04-28 16:28:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitLocSupplied','en','lava','crms-import',NULL,'importDefinition','visitLocSupplied',NULL,'i','toggle',NULL,'Visit Location Supplied in Data File',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Location Supplied in Data File','2014-04-28 16:29:41');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitLoc','en','lava','crms-import',NULL,'importDefinition','visitLoc',NULL,'i','suggest',NULL,'Visit Location',NULL,NULL,NULL,0,NULL,'visit.locations',NULL,NULL,'Visit Location','2014-04-28 16:31:38');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitStatusSupplied','en','lava','crms-import',NULL,'importDefinition','visitStatusSupplied',NULL,'i','toggle',NULL,'Visit Status Supplied',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Status Supplied','2014-04-28 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitStatus','en','lava','crms-import',NULL,'importDefinition','visitStatus',NULL,'i','range',NULL,'Visit Status',NULL,NULL,NULL,0,NULL,'visit.status',NULL,NULL,'Visit Status','2014-04-28 16:35:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrMustExist','en','lava','crms-import',NULL,'importDefinition','instrMustExist',NULL,'i','toggle',NULL,'Instrument Must Exist',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Instrument Must Exist','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType','en','lava','crms-import',NULL,'importDefinition','instrType',NULL,'i','range','Yes','Instrument',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument for imported data','2014-04-28 16:08:27');

