DELETE FROM viewproperty WHERE scope = 'crms-import';
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importSetup.projName','en','lava','crms-import',NULL,'importSetup','projName',NULL,'i','range','Yes','Project',NULL,NULL,NULL,0,NULL,'enrollmentStatus.patientProjects',NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.patientMustExist','en','lava','crms-import',NULL,'importTemplate','patientMustExist',NULL,'i','toggle',NULL,'Patient Must Exist',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Patient Must Exist','2014-04-28 16:11:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.projNameForContext','en','lava','crms-import',NULL,'importTemplate','projNameForContext',NULL,'i','range',NULL,'Project',NULL,NULL,NULL,0,NULL,'enrollmentStatus.patientProjects',NULL,NULL,'Project Context for Visit Data','2014-04-28 16:13:30');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitMustExist','en','lava','crms-import',NULL,'importTemplate','visitMustExist',NULL,'i','toggle',NULL,'Visit Must Exist',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Must Exist','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitTypeSupplied','en','lava','crms-import',NULL,'importTemplate','visitTypeSupplied',NULL,'i','toggle',NULL,'Visit Type Supplied in Data File',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Type Supplied in Data File','2014-04-28 16:20:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitType','en','lava','crms-import',NULL,'importTemplate','visitType',NULL,'i','range',NULL,'Visit Type',NULL,NULL,NULL,0,NULL,'visit.visitTypes',NULL,NULL,'Visit Type','2014-04-28 16:21:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate. visitWithSupplied','en','lava','crms-import',NULL,'importTemplate','visitWithSupplied',NULL,'i','toggle',NULL,'Appt With Supplied in Data File',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Appt With Supplied in Data File','2014-04-28 16:25:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitWith','en','lava','crms-import',NULL,'importTemplate','visitWith',NULL,'i','suggest',NULL,'Appt With',NULL,NULL,NULL,0,NULL,'project.staffList',NULL,NULL,'Appointment With','2014-04-28 16:28:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitLocSupplied','en','lava','crms-import',NULL,'importTemplate','visitLocSupplied',NULL,'i','toggle',NULL,'Visit Location Supplied in Data File',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Location Supplied in Data File','2014-04-28 16:29:41');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitLoc','en','lava','crms-import',NULL,'importTemplate','visitLoc',NULL,'i','suggest',NULL,'Visit Location',NULL,NULL,NULL,0,NULL,'visit.locations',NULL,NULL,'Visit Location','2014-04-28 16:31:38');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitStatusSupplied','en','lava','crms-import',NULL,'importTemplate','visitStatusSupplied',NULL,'i','toggle',NULL,'Visit Status Supplied',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Visit Status Supplied','2014-04-28 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importTemplate.visitStatus','en','lava','crms-import',NULL,'importTemplate','visitStatus',NULL,'i','range',NULL,'Visit Status',NULL,NULL,NULL,0,NULL,'visit.status',NULL,NULL,'Visit Status','2014-04-28 16:35:50');

