<%--
  - Saves a bunch of reusable values to the request scope.
  --%>

<%@ page import="java.util.*" %>

<%
////////// countryList //////////
Map countryList = new TreeMap();
request.setAttribute("countryList", countryList);
countryList.put("Afghanistan", "Afghanistan");
countryList.put("Albania", "Albania");
countryList.put("Algeria", "Algeria");
countryList.put("Andorra", "Andorra");
countryList.put("Angola", "Angola");
countryList.put("AntiguaAndBarbuda", "Antigua and Barbuda");
countryList.put("Argentina", "Argentina");
countryList.put("Armenia", "Armenia");
countryList.put("Australia", "Australia");
countryList.put("Austria", "Austria");
countryList.put("Azerbaijan", "Azerbaijan");
countryList.put("Bahamas", "Bahamas");
countryList.put("Bahrain", "Bahrain");
countryList.put("Bangladesh", "Bangladesh");
countryList.put("Barbados", "Barbados");
countryList.put("Belarus", "Belarus");
countryList.put("Belgium", "Belgium");
countryList.put("Belize", "Belize");
countryList.put("Benin", "Benin");
countryList.put("Bhutan", "Bhutan");
countryList.put("Bolivia", "Bolivia");
countryList.put("BosniaAndHerzegovina", "Bosnia and Herzegovina");
countryList.put("Botswana", "Botswana");
countryList.put("Brazil", "Brazil");
countryList.put("Brunei", "Brunei");
countryList.put("Bulgaria", "Bulgaria");
countryList.put("BurkinaFaso", "Burkina Faso");
countryList.put("BurmaMyanmar", "Burma/Myanmar");
countryList.put("Burundi", "Burundi");
countryList.put("Cambodia", "Cambodia");
countryList.put("Cameroon", "Cameroon");
countryList.put("Canada", "Canada");
countryList.put("CapeVerde", "Cape Verde");
countryList.put("CentralAfricanRepublic", "Central African Republic");
countryList.put("Chad", "Chad");
countryList.put("Chile", "Chile");
countryList.put("China", "China");
countryList.put("Colombia", "Colombia");
countryList.put("Comoros", "Comoros");
countryList.put("Congo", "Congo");
countryList.put("CongoDemocraticRepublicOf", "Congo, Democratic Republic of");
countryList.put("CostaRica", "Costa Rica");
countryList.put("Croatia", "Croatia");
countryList.put("CoteDIvoire", "Cote d'Ivoire");
countryList.put("Cuba", "Cuba");
countryList.put("Cyprus", "Cyprus");
countryList.put("CzechRepublic", "Czech Republic");
countryList.put("Denmark", "Denmark");
countryList.put("Djibouti", "Djibouti");
countryList.put("Dominica", "Dominica");
countryList.put("DominicanRepublic", "Dominican Republic");
countryList.put("EastTimor", "East Timor");
countryList.put("Ecuador", "Ecuador");
countryList.put("Egypt", "Egypt");
countryList.put("ElSalvador", "El Salvador");
countryList.put("EquatorialGuinea", "Equatorial Guinea");
countryList.put("Eritrea", "Eritrea");
countryList.put("Estonia", "Estonia");
countryList.put("Ethiopia", "Ethiopia");
countryList.put("Fiji", "Fiji");
countryList.put("Finland", "Finland");
countryList.put("France", "France");
countryList.put("Gabon", "Gabon");
countryList.put("Gambia", "Gambia");
countryList.put("Georgia", "Georgia");
countryList.put("Germany", "Germany");
countryList.put("Ghana", "Ghana");
countryList.put("Greece", "Greece");
countryList.put("Grenada", "Grenada");
countryList.put("Guatemala", "Guatemala");
countryList.put("Guinea", "Guinea");
countryList.put("GuineaBissau", "Guinea-Bissau");
countryList.put("Guyana", "Guyana");
countryList.put("Haiti", "Haiti");
countryList.put("Honduras", "Honduras");
countryList.put("Hungary", "Hungary");
countryList.put("Iceland", "Iceland");
countryList.put("India", "India");
countryList.put("Indonesia", "Indonesia");
countryList.put("Iran", "Iran");
countryList.put("Iraq", "Iraq");
countryList.put("Ireland", "Ireland");
countryList.put("Israel", "Israel");
countryList.put("Italy", "Italy");
countryList.put("IvoryCoast", "Ivory Coast");
countryList.put("Jamaica", "Jamaica");
countryList.put("Japan", "Japan");
countryList.put("Jordan", "Jordan");
countryList.put("Kazakstan", "Kazakstan");
countryList.put("Kenya", "Kenya");
countryList.put("Kiribati", "Kiribati");
countryList.put("NorthKorea", "Korea, North");
countryList.put("SouthKorea", "Korea, South");
countryList.put("Kuwait", "Kuwait");
countryList.put("Kyrgyzstan", "Kyrgyzstan");
countryList.put("Laos", "Laos");
countryList.put("Latvia", "Latvia");
countryList.put("Lebanon", "Lebanon");
countryList.put("Lesotho", "Lesotho");
countryList.put("Liberia", "Liberia");
countryList.put("Libya", "Libya");
countryList.put("Liechtenstein", "Liechtenstein");
countryList.put("Lithuania", "Lithuania");
countryList.put("Luxembourg", "Luxembourg");
countryList.put("Macedonia", "Macedonia");
countryList.put("Madagascar", "Madagascar");
countryList.put("Malawi", "Malawi");
countryList.put("Malaysia", "Malaysia");
countryList.put("Maldives", "Maldives");
countryList.put("Mali", "Mali");
countryList.put("Malta", "Malta");
countryList.put("MarshallIslands", "Marshall Islands");
countryList.put("Mauritania", "Mauritania");
countryList.put("Mauritius", "Mauritius");
countryList.put("Mexico", "Mexico");
countryList.put("Micronesia", "Micronesia");
countryList.put("Moldova", "Moldova");
countryList.put("Monaco", "Monaco");
countryList.put("Mongolia", "Mongolia");
countryList.put("Morocco", "Morocco");
countryList.put("Mozambique", "Mozambique");
countryList.put("Namibia", "Namibia");
countryList.put("Nauru", "Nauru");
countryList.put("Nepal", "Nepal");
countryList.put("Netherlands", "Netherlands");
countryList.put("NewZealand", "New Zealand");
countryList.put("Nicaragua", "Nicaragua");
countryList.put("Niger", "Niger");
countryList.put("Nigeria", "Nigeria");
countryList.put("Norway", "Norway");
countryList.put("Oman", "Oman");
countryList.put("Pakistan", "Pakistan");
countryList.put("Palau", "Palau");
countryList.put("Panama", "Panama");
countryList.put("PapuaNewGuinea", "Papua New Guinea");
countryList.put("Paraguay", "Paraguay");
countryList.put("Peru", "Peru");
countryList.put("Philippines", "Philippines");
countryList.put("Poland", "Poland");
countryList.put("Portugal", "Portugal");
countryList.put("Qatar", "Qatar");
countryList.put("Romania", "Romania");
countryList.put("RussianFederation", "Russian Federation");
countryList.put("Rwanda", "Rwanda");
countryList.put("SaintKittsAndNevis", "Saint Kitts and Nevis");
countryList.put("SaintLucia", "Saint Lucia");
countryList.put("SaintVincentAndTheGrenadines", "Saint Vincent and the Grenadines");
countryList.put("Samoa", "Samoa");
countryList.put("SanMarino", "San Marino");
countryList.put("SaoTomeAndPrincipe", "Sao Tome and Principe");
countryList.put("SaudiArabia", "Saudi Arabia");
countryList.put("Senegal", "Senegal");
countryList.put("Seychelles", "Seychelles");
countryList.put("SierraLeone", "Sierra Leone");
countryList.put("Singapore", "Singapore");
countryList.put("Slovakia", "Slovakia");
countryList.put("Slovenia", "Slovenia");
countryList.put("SolomonIslands", "Solomon Islands");
countryList.put("Somalia", "Somalia");
countryList.put("SouthAfrica", "South Africa");
countryList.put("Spain", "Spain");
countryList.put("SriLanka", "Sri Lanka");
countryList.put("Sudan", "Sudan");
countryList.put("Suriname", "Suriname");
countryList.put("Swaziland", "Swaziland");
countryList.put("Sweden", "Sweden");
countryList.put("Switzerland", "Switzerland");
countryList.put("Syria", "Syria");
countryList.put("Taiwan", "Taiwan");
countryList.put("Tajikistan", "Tajikistan");
countryList.put("Tanzania", "Tanzania");
countryList.put("Thailand", "Thailand");
countryList.put("Togo", "Togo");
countryList.put("Tonga", "Tonga");
countryList.put("TrinidadAndTobago", "Trinidad and Tobago");
countryList.put("Tunisia", "Tunisia");
countryList.put("Turkey", "Turkey");
countryList.put("Turkmenistan", "Turkmenistan");
countryList.put("Tuvalu", "Tuvalu");
countryList.put("Uganda", "Uganda");
countryList.put("Ukraine", "Ukraine");
countryList.put("UnitedArabEmirates", "United Arab Emirates");
countryList.put("UnitedKingdom", "United Kingdom");
countryList.put("UnitedStates", "United States");
countryList.put("Uruguay", "Uruguay");
countryList.put("Uzbekistan", "Uzbekistan");
countryList.put("Vanuatu", "Vanuatu");
countryList.put("VaticanCity", "Vatican City");
countryList.put("Venezuela", "Venezuela");
countryList.put("Vietnam", "Vietnam");
countryList.put("Yemen", "Yemen");
countryList.put("Yugoslavia", "Yugoslavia");
countryList.put("Zambia", "Zambia");
countryList.put("Zimbabwe", "Zimbabwe");


request.setAttribute("commonJs", "/uitags.js");
request.setAttribute("comboDatePickerJs", "/comboDatePicker.js");
request.setAttribute("comboOptionTransferJs", "/comboOptionTransfer.js");

%>