SELECT CONCAT('ALTER TABLE `',TABLE_NAME,
'` ADD CONSTRAINT `',TABLE_NAME,'__InstrID` 
 FOREIGN KEY (`InstrID` )
 REFERENCES `instrumenttracking` (`InstrID` )
 ON DELETE NO ACTION
 ON UPDATE NO ACTION',', ADD INDEX `',TABLE_NAME,'__InstrID` (`InstrID` ASC) ;') 
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='DEMO' and TABLE_TYPE='BASE TABLE';




SELECT CONCAT('ALTER TABLE `',TABLE_NAME,
'` DROP FOREIGN KEY `',TABLE_NAME,'__InstrID`,
 DROP INDEX `',TABLE_NAME,'`;')
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='DEMO' and TABLE_TYPE='BASE TABLE';

SELECT CONCAT('ALTER TABLE `',TABLE_NAME,
'` DROP INDEX `',TABLE_NAME,'__InstrID`;')
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='DEMO' and TABLE_TYPE='BASE TABLE';