-- add these crms properties to addPatient
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.addPatient.patient_title','en','lava','crms',NULL,'addPatient','patient_title','ID and Core Demographics','i','range','No','Title',NULL,NULL,NULL,0,'','generic.nameTitle',NULL,NULL,'','2013-04-10 01:16:03');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.addPatient.patient_educ','en','lava','crms',NULL,'addPatient','patient_educ','Personal History/Current Arrangements','i','range','No','Education',NULL,NULL,NULL,0,'','generic.education',NULL,2,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.addPatient.patient_age','en','lava','crms',NULL,'addPatient','patient_age','ID and Core Demographics','c','numeric','No','Age',NULL,NULL,NULL,0,'','',NULL,10,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.addPatient.patient_createdBy','en','lava','crms',NULL,'addPatient','patient_createdBy','Record Management','i','range','No','Created By',NULL,NULL,NULL,0,'','patient.staffList',NULL,17,'User who created patient record','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.addPatient.patient_race','en','lava','crms',NULL,'addPatient','patient_race','Racial Demographics','i','range','No','Race',NULL,NULL,NULL,0,'','generic.race',NULL,6,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.addPatient.patient_dupNameFlag','en','lava','crms',NULL,'addPatient','patient_dupNameFlag','Record Management','i','scale','Yes','Dup Name Warning',NULL,NULL,NULL,0,'','generic.yesNoZero',NULL,18,'','2009-01-24 21:28:51');

DELETE FROM versionhistory WHERE module='lava-crms-data' AND version='3.5.2';
INSERT INTO versionhistory(`Module`,`Version`,`VersionDate`,`Major`,`Minor`,`Fix`,`UpdateRequired`)
VALUES ('lava-crms-data','3.5.2','2015-02-08',3,5,2,0);


