INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.created','en','lava','crms',NULL,'patient','created','','c','date','No','Created',NULL,NULL,NULL,0,'','',NULL,NULL,'','2014-07-11 18:13:26');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.createdBy','en','lava','crms',NULL,'patient','createdBy','Record Management','i','range','No','Entered By',NULL,NULL,NULL,0,'','patient.staffList',NULL,17,'','2009-01-24 21:28:51');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.familyId','en','lava','crms',NULL,'Patient','familyId','','i','range','No','Family',NULL,NULL,NULL,0,NULL,'patient.familyIds',NULL,NULL,'Family','2014-07-11 19:55:14');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.familyStatus','en','lava','crms',NULL,'Patient','familyStatus','','i','range','No','Family Status',NULL,NULL,NULL,0,NULL,'patient.familyStatus',NULL,NULL,'Family Status','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.familyStudy','en','lava','crms',NULL,'Patient','familyStudy','','i','string','No','Family Study',NULL,50,NULL,0,NULL,NULL,NULL,NULL,'Family Study','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.relationToProband','en','lava','crms',NULL,'Patient','relationToProband','','i','range','No','Relation to Proband',NULL,NULL,NULL,0,NULL,'patient.relationToProband',NULL,NULL,'Relation to Proband','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.probandCandidate','en','lava','crms',NULL,'Patient','probandCandidate','','i','range','No','Proband Candidate',NULL,NULL,NULL,0,NULL,'generic.yesNoZero',NULL,NULL,'Proband Candidate','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.twin','en','lava','crms',NULL,'Patient','twin','','i','range','No','Twin',NULL,NULL,NULL,0,NULL,'generic.yesNoZero',NULL,NULL,'Is patient a twin?','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.twinZygosity','en','lava','crms',NULL,'Patient','twinZygosity','','i','range','No','Twin Zygosity',NULL,NULL,NULL,0,NULL,'patient.twinZygosity',NULL,NULL,'Twin Zygosity','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.twinId','en','lava','crms',NULL,'Patient','twinId','','i','string','No','Twin ID',NULL,2,2,0,NULL,NULL,NULL,NULL,'Twin ID','2014-07-11 19:55:15');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.patient.relationNotes','en','lava','crms',NULL,'Patient','relationNotes','','i','text','No','Relation Notes',NULL,100,NULL,0,'rows="2" cols="50"',NULL,NULL,NULL,'Relation Notes','2014-07-11 19:55:15');


