-- fix up some metadata changes that somehow got lost
UPDATE viewproperty SET label='Created By',quickHelp='User who created patient record'  
  WHERE messageCode='*.patient.createdBy'; 
UPDATE viewproperty SET size = 40 WHERE entity = 'instrument' AND property = 'instrType';
DELETE FROM `viewproperty` WHERE `messageCode` = 'filter.visit.quickFilter';
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,
`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`) 
VALUES('filter.visit.quickFilter','en','lava','crms','filter','visit','quickFilter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'visit.quickFilter',NULL,NULL,NULL);

-- changes in getting attachments working
UPDATE viewproperty SET label = 'Content Type' WHERE entity = 'crmsFile' AND property = 'contentType';
UPDATE viewproperty SET context = 'c' WHERE entity = 'crmsFile' AND property = 'name';

-- changed length of subjectStudyId
UPDATE viewproperty SET maxLength = 25 WHERE entity = 'enrollmentStatus' AND property = 'subjectStudyId';

-- doctor firstName no longer required
UPDATE viewproperty SET required = 'No' WHERE entity = 'doctor' AND property = 'firstName';

-- import properties metadata
DELETE from `viewproperty` where `instance`='lava' and `scope`='crms' and entity in ('import','importDefinition','importLog');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.projName','en','lava','crms',NULL,'importDefinition','projName',NULL,'i','range','Yes','Project',NULL,NULL,NULL,0,NULL,'context.projectList',NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowPatientUpdate','en','lava','crms',NULL,'importDefinition','allowPatientUpdate',NULL,'i','toggle',NULL,'Update Existing Patient',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Patient','2014-04-28 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitStatus','en','lava','crms',NULL,'importDefinition','visitStatus',NULL,'i','range',NULL,'Visit Status',NULL,NULL,NULL,0,NULL,'visit.status',NULL,NULL,'Visit Status','2014-04-28 16:35:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrExistRule','en','lava','crms',NULL,'importDefinition','instrExistRule',NULL,'i','scale',NULL,'Instrument Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Instrument Exists Rule','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType','en','lava','crms',NULL,'importDefinition','instrType',NULL,'i','range','Yes','Instrument',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.esExistRule','en','lava','crms',NULL,'importDefinition','esExistRule',NULL,'i','scale',NULL,'Enrollment Status Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Enrollment Status Exists Rule','2014-05-24 21:31:39');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowEsUpdate','en','lava','crms',NULL,'importDefinition','allowEsUpdate',NULL,'i','toggle',NULL,'Update Existing Enrollment Status',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Enrollment Status','2014-05-24 21:33:14');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.esStatus','en','lava','crms',NULL,'importDefinition','esStatus',NULL,'i','range',NULL,'Enrollment Status',NULL,NULL,NULL,0,NULL,'enrollmentStatus.projectStatus',NULL,NULL,'Enrollment Status','2014-05-24 21:35:32');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer','en','lava','crms',NULL,'importDefinition','instrVer',NULL,'i','numeric',NULL,'Instrument Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowInstrUpdate','en','lava','crms',NULL,'importDefinition','allowInstrUpdate',NULL,'i','toggle',NULL,'Update Existing Instrument',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Instrument','2014-05-24 22:40:33');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrDcStatus','en','lava','crms',NULL,'importDefinition','instrDcStatus',NULL,'i','range',NULL,'Instrument Data Collection Status',NULL,NULL,NULL,0,NULL,'instrument.dcStatus',NULL,NULL,'Instrument Data Collection Status','2014-05-24 22:41:42');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.patientExistRule','en','lava','crms',NULL,'importDefinition','patientExistRule',NULL,'i','scale',NULL,'Patient Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Patient Exists Rule','2014-04-28 16:11:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.projNameForContext','en','lava','crms',NULL,'importDefinition','projNameForContext',NULL,'i','range',NULL,'Project',NULL,NULL,NULL,0,NULL,'context.projectList',NULL,NULL,'Project Context for Visit Data','2014-04-28 16:13:30');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitExistRule','en','lava','crms',NULL,'importDefinition','visitExistRule',NULL,'i','scale',NULL,'Visit Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Visit Exists Rule','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowVisitUpdate','en','lava','crms',NULL,'importDefinition','allowVisitUpdate',NULL,'i','toggle',NULL,'Update Existing Visit',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Visit','2014-04-28 16:20:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitType','en','lava','crms',NULL,'importDefinition','visitType',NULL,'i','range',NULL,'Visit Type',NULL,NULL,NULL,0,NULL,'visit.visitTypes',NULL,NULL,'Visit Type','2014-04-28 16:21:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitWith','en','lava','crms',NULL,'importDefinition','visitWith',NULL,'i','suggest',NULL,'Appt With',NULL,NULL,NULL,0,NULL,'project.staffList',NULL,NULL,'Appointment With','2014-04-28 16:28:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitLoc','en','lava','crms',NULL,'importDefinition','visitLoc',NULL,'i','suggest',NULL,'Visit Location',NULL,NULL,NULL,0,NULL,'visit.visitLocations',NULL,NULL,'Visit Location','2014-04-28 16:31:38');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.projName','en','lava','crms',NULL,'importLog','projName',NULL,'c','string',NULL,'Project',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.totalRecords','en','lava','crms',NULL,'importLog','totalRecords',NULL,'c','numeric',NULL,'Total records in data file',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Total records in data file','2014-07-22 16:46:31');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.imported','en','lava','crms',NULL,'importLog','imported',NULL,'c','numeric',NULL,'Records imported',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Number of records imported','2014-07-22 16:47:53');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.alreadyExist','en','lava','crms',NULL,'importLog','alreadyExist',NULL,'c','numeric',NULL,'Already existing records (i.e. not imported)',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Number of already existing records (i.e. not imported)','2014-07-22 16:49:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.errors','en','lava','crms',NULL,'importLog','errors',NULL,'c','numeric',NULL,'Records with errors (i.e. could not be imported)',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Number of records with errors (i.e. could not be imported)','2014-07-22 16:51:24');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.warnings','en','lava','crms',NULL,'importLog','warnings',NULL,'c','numeric',NULL,'Records with warnings (record was imported)',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Number of records with warnings (record was imported)','2014-07-22 16:52:36');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newPatients','en','lava','crms',NULL,'importLog','newPatients',NULL,'c','numeric',NULL,'New Patients Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Patients Created','2014-07-22 16:54:24');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingPatients','en','lava','crms',NULL,'importLog','existingPatients',NULL,'c','numeric',NULL,'Already Existing Patients',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Patients','2014-07-22 16:55:26');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newContactInfo','en','lava','crms',NULL,'importLog','newContactInfo',NULL,'c','numeric',NULL,'New Contact Info Records Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Contact Info Records Created','2014-07-22 16:56:46');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingContactInfo','en','lava','crms',NULL,'importLog','existingContactInfo',NULL,'c','numeric',NULL,'Already Existing Contact Info Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Contact Info Records','2014-07-22 16:57:58');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newCaregivers','en','lava','crms',NULL,'importLog','newCaregivers',NULL,'c','numeric',NULL,'New Caregiver Records Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Caregiver Records Created','2014-07-22 16:59:19');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingCaregivers','en','lava','crms',NULL,'importLog','existingCaregivers',NULL,'c','numeric',NULL,'Already Existing Caretiver Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Caretiver Records','2014-07-22 17:00:40');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newCaregiversContactInfo','en','lava','crms',NULL,'importLog','newCaregiversContactInfo',NULL,'c','numeric',NULL,'New Caregiver Contact Info Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Caregiver Contact Info Records','2014-07-22 17:02:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingCaregiversContactInfo','en','lava','crms',NULL,'importLog','existingCaregiversContactInfo',NULL,'c','numeric',NULL,'Already Existing Caregiver Contact Info Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Caregiver Contact Info Records','2014-07-22 17:03:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newEnrollmentStatuses','en','lava','crms',NULL,'importLog','newEnrollmentStatuses',NULL,'c','numeric',NULL,'New Enrollment Status Records Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Enrollment Status Records Created','2014-07-22 17:04:38');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingEnrollmentStatuses','en','lava','crms',NULL,'importLog','existingEnrollmentStatuses',NULL,'c','numeric',NULL,'Already Existing Enrollment Status Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Enrollment Status Records','2014-07-22 17:05:52');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newVisits','en','lava','crms',NULL,'importLog','newVisits',NULL,'c','numeric',NULL,'New Visits Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Visits Created','2014-07-22 17:06:52');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingVisits','en','lava','crms',NULL,'importLog','existingVisits',NULL,'c','numeric',NULL,'Already Existing Visits',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Visits','2014-07-22 17:08:22');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newInstruments','en','lava','crms',NULL,'importLog','newInstruments',NULL,'c','numeric',NULL,'New Instruments Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Instruments Created','2014-07-22 17:09:37');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingInstruments','en','lava','crms',NULL,'importLog','existingInstruments',NULL,'c','numeric',NULL,'Already Exisitng Instruments',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Instruments','2014-07-22 17:11:00');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingInstrumentsWithData','en','lava','crms',NULL,'importLog','existingInstrumentsWithData',NULL,'c','numeric',NULL,'Already Existing Instruments With Data',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Instruments With Data','2014-07-22 17:14:34');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.updated','en','lava','crms',NULL,'importLog','updated',NULL,'c','numeric',NULL,'Records Updated',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Records Updated','2014-07-22 22:30:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.type','en','lava','crms',NULL,'importLog','type',NULL,'c','string',NULL,'Type',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Log Message Type','2014-07-23 23:41:53');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.lineNum','en','lava','crms',NULL,'importLog','lineNum',NULL,'c','numeric',NULL,'Line Number',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Data File Line Number','2014-07-23 23:44:30');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.message','en','lava','crms',NULL,'importLog','message',NULL,'c','string',NULL,'Message',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Log Message','2014-07-23 23:49:33');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.summaryBlock','en','lava','crms',NULL,'importLog','summaryBlock',NULL,'c','string',NULL,'Summary',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Import Summary Stars','2014-07-24 01:19:05');

DELETE FROM versionhistory WHERE module='lava-crms-data' AND version='3.5.0';
INSERT INTO versionhistory(`Module`,`Version`,`VersionDate`,`Major`,`Minor`,`Fix`,`UpdateRequired`)
VALUES ('lava-crms-data','3.5.0',NOW(),3,5,0,0);

