-- NOTE: alternatively to this script, can just use the lava-app-pedi 
-- database/local/crms/development/data/extract-crms-data.sql extract script to generate 
-- lava-crms-data-VERSION.sql for transferring all metadata changes. easier as opposed to 
-- adding individual changes to a script like this, but then again a script like this makes it
-- clear what metadata was added, changed, deleted

-- fix up some metadata changes that somehow got lost
UPDATE viewproperty SET label='Created By',quickHelp='User who created patient record'  
  WHERE messageCode='*.patient.createdBy'; 
UPDATE viewproperty SET size = 40 WHERE entity = 'instrument' AND property = 'instrType';
DELETE FROM `viewproperty` WHERE `messageCode` = 'filter.visit.quickFilter';
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,
`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`) 
VALUES('filter.visit.quickFilter','en','lava','crms','filter','visit','quickFilter',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'visit.quickFilter',NULL,NULL,NULL);

-- changes in getting attachments working
UPDATE viewproperty SET label = 'Content Type' WHERE entity = 'crmsFile' AND property = 'contentType';
UPDATE viewproperty SET context = 'c' WHERE entity = 'crmsFile' AND property = 'name';

-- changed length of subjectStudyId
UPDATE viewproperty SET maxLength = 25 WHERE entity = 'enrollmentStatus' AND property = 'subjectStudyId';

-- doctor firstName no longer required
UPDATE viewproperty SET required = 'No' WHERE entity = 'doctor' AND property = 'firstName';

-- import properties metadata
DELETE from `viewproperty` where `instance`='lava' and `scope`='crms' and entity in ('import','importDefinition','importLog');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.projName','en','lava','crms',NULL,'importDefinition','projName',NULL,'i','range','Yes','Project',NULL,NULL,NULL,0,NULL,'context.projectList',NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowPatientUpdate','en','lava','crms',NULL,'importDefinition','allowPatientUpdate',NULL,'i','toggle',NULL,'Update Existing Patient',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Patient','2014-04-28 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitStatus','en','lava','crms',NULL,'importDefinition','visitStatus',NULL,'i','range',NULL,'Visit Status',NULL,NULL,NULL,0,NULL,'visit.status',NULL,NULL,'Visit Status','2014-04-28 16:35:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrExistRule','en','lava','crms',NULL,'importDefinition','instrExistRule',NULL,'i','scale',NULL,'Instrument Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Instrument Exists Rule','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType','en','lava','crms',NULL,'importDefinition','instrType',NULL,'i','range','Yes','Instrument',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.esExistRule','en','lava','crms',NULL,'importDefinition','esExistRule',NULL,'i','scale',NULL,'Enrollment Status Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Enrollment Status Exists Rule','2014-05-24 21:31:39');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowEsUpdate','en','lava','crms',NULL,'importDefinition','allowEsUpdate',NULL,'i','toggle',NULL,'Update Existing Enrollment Status',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Enrollment Status','2014-05-24 21:33:14');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.esStatus','en','lava','crms',NULL,'importDefinition','esStatus',NULL,'i','range',NULL,'Enrollment Status',NULL,NULL,NULL,0,NULL,'enrollmentStatus.projectStatus',NULL,NULL,'Enrollment Status','2014-05-24 21:35:32');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer','en','lava','crms',NULL,'importDefinition','instrVer',NULL,'i','numeric',NULL,'Instrument Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowInstrUpdate','en','lava','crms',NULL,'importDefinition','allowInstrUpdate',NULL,'i','toggle',NULL,'Update Existing Instrument',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Instrument','2014-05-24 22:40:33');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrDcStatus','en','lava','crms',NULL,'importDefinition','instrDcStatus',NULL,'i','range',NULL,'Instrument Data Collection Status',NULL,NULL,NULL,0,NULL,'instrument.dcStatus',NULL,NULL,'Instrument Data Collection Status','2014-05-24 22:41:42');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.patientExistRule','en','lava','crms',NULL,'importDefinition','patientExistRule',NULL,'i','scale',NULL,'Patient Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Patient Exists Rule','2014-04-28 16:11:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.projNameForContext','en','lava','crms',NULL,'importDefinition','projNameForContext',NULL,'i','range',NULL,'Project',NULL,NULL,NULL,0,NULL,'context.projectList',NULL,NULL,'Project Context for Visit Data','2014-04-28 16:13:30');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitExistRule','en','lava','crms',NULL,'importDefinition','visitExistRule',NULL,'i','scale',NULL,'Visit Exists Rule',NULL,NULL,NULL,0,NULL,'importDefinition.existRules',NULL,NULL,'Visit Exists Rule','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitWindow','en','lava','crms',NULL,'importDefinition','visitWindow',NULL,'i','range',NULL,'Visit Match Window (+/- Days)',NULL,NULL,NULL,0,NULL,'importDefinition.visitMatchRange',NULL,NULL,'Match Visit Within +/- Days from Visit Date in Data File','2014-04-28 16:15:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.allowVisitUpdate','en','lava','crms',NULL,'importDefinition','allowVisitUpdate',NULL,'i','toggle',NULL,'Update Existing Visit',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Update Existing Visit','2014-04-28 16:20:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitType','en','lava','crms',NULL,'importDefinition','visitType',NULL,'i','range',NULL,'Visit Type',NULL,NULL,NULL,0,NULL,'visit.visitTypes',NULL,NULL,'Visit Type','2014-04-28 16:21:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.matchVisitType','en','lava','crms',NULL,'importDefinition','matchVisitType',NULL,'i','toggle',NULL,'Match on Visit Type',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Match Existing Visit on Visit Type','2014-04-28 16:21:50');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitWith','en','lava','crms',NULL,'importDefinition','visitWith',NULL,'i','suggest',NULL,'Appt With',NULL,NULL,NULL,0,NULL,'project.staffList',NULL,NULL,'Appointment With','2014-04-28 16:28:08');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.visitLoc','en','lava','crms',NULL,'importDefinition','visitLoc',NULL,'i','suggest',NULL,'Visit Location',NULL,NULL,NULL,0,NULL,'visit.visitLocations',NULL,NULL,'Visit Location','2014-04-28 16:31:38');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType2','en','lava','crms',NULL,'importDefinition','instrType2',NULL,'i','range','Yes','Instrument 2',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 2 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer2','en','lava','crms',NULL,'importDefinition','instrVer2',NULL,'i','numeric',NULL,'Instrument 2 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 2 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType3','en','lava','crms',NULL,'importDefinition','instrType3',NULL,'i','range','Yes','Instrument 3',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 3 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer3','en','lava','crms',NULL,'importDefinition','instrVer3',NULL,'i','numeric',NULL,'Instrument 3 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 3 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType4','en','lava','crms',NULL,'importDefinition','instrType4',NULL,'i','range','Yes','Instrument 4',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 4 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer4','en','lava','crms',NULL,'importDefinition','instrVer4',NULL,'i','numeric',NULL,'Instrument 4 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 4 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType5','en','lava','crms',NULL,'importDefinition','instrType5',NULL,'i','range','Yes','Instrument 5',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 5 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer5','en','lava','crms',NULL,'importDefinition','instrVer5',NULL,'i','numeric',NULL,'Instrument 5 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 5 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType6','en','lava','crms',NULL,'importDefinition','instrType6',NULL,'i','range','Yes','Instrument 6',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 6 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer6','en','lava','crms',NULL,'importDefinition','instrVer6',NULL,'i','numeric',NULL,'Instrument 6 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 6 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType7','en','lava','crms',NULL,'importDefinition','instrType7',NULL,'i','range','Yes','Instrument 7',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 7 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer7','en','lava','crms',NULL,'importDefinition','instrVer7',NULL,'i','numeric',NULL,'Instrument 7 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 7 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType8','en','lava','crms',NULL,'importDefinition','instrType8',NULL,'i','range','Yes','Instrument 8',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 8 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer8','en','lava','crms',NULL,'importDefinition','instrVer8',NULL,'i','numeric',NULL,'Instrument 8 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 8 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType9','en','lava','crms',NULL,'importDefinition','instrType9',NULL,'i','range','Yes','Instrument 9',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 9 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer9','en','lava','crms',NULL,'importDefinition','instrVer9',NULL,'i','numeric',NULL,'Instrument 9 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 9 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrType10','en','lava','crms',NULL,'importDefinition','instrType10',NULL,'i','range','Yes','Instrument 10',NULL,NULL,NULL,0,NULL,'instrumentMetadata.instrTypes',NULL,NULL,'Instrument 10 for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importDefinition.instrVer10','en','lava','crms',NULL,'importDefinition','instrVer10',NULL,'i','numeric',NULL,'Instrument 10 Version',NULL,NULL,NULL,0,'onkeypress="onlyNumsAllowed(event)"',NULL,NULL,NULL,'Version for New Instrument 10 Records','2014-05-24 22:09:25');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.projName','en','lava','crms',NULL,'importLog','projName',NULL,'c','string',NULL,'Project',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Project for imported data','2014-04-28 16:08:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newPatients','en','lava','crms',NULL,'importLog','newPatients',NULL,'c','numeric',NULL,'New Patients Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Patients Created','2014-07-22 16:54:24');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingPatients','en','lava','crms',NULL,'importLog','existingPatients',NULL,'c','numeric',NULL,'Already Existing Patients',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Patients','2014-07-22 16:55:26');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newContactInfo','en','lava','crms',NULL,'importLog','newContactInfo',NULL,'c','numeric',NULL,'New Contact Info Records Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Contact Info Records Created','2014-07-22 16:56:46');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingContactInfo','en','lava','crms',NULL,'importLog','existingContactInfo',NULL,'c','numeric',NULL,'Already Existing Contact Info Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Contact Info Records','2014-07-22 16:57:58');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newCaregivers','en','lava','crms',NULL,'importLog','newCaregivers',NULL,'c','numeric',NULL,'New Caregiver Records Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Caregiver Records Created','2014-07-22 16:59:19');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingCaregivers','en','lava','crms',NULL,'importLog','existingCaregivers',NULL,'c','numeric',NULL,'Already Existing Caretiver Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Caretiver Records','2014-07-22 17:00:40');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newCaregiversContactInfo','en','lava','crms',NULL,'importLog','newCaregiversContactInfo',NULL,'c','numeric',NULL,'New Caregiver Contact Info Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Caregiver Contact Info Records','2014-07-22 17:02:01');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingCaregiversContactInfo','en','lava','crms',NULL,'importLog','existingCaregiversContactInfo',NULL,'c','numeric',NULL,'Already Existing Caregiver Contact Info Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Caregiver Contact Info Records','2014-07-22 17:03:27');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newEnrollmentStatuses','en','lava','crms',NULL,'importLog','newEnrollmentStatuses',NULL,'c','numeric',NULL,'New Enrollment Status Records Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Enrollment Status Records Created','2014-07-22 17:04:38');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingEnrollmentStatuses','en','lava','crms',NULL,'importLog','existingEnrollmentStatuses',NULL,'c','numeric',NULL,'Already Existing Enrollment Status Records',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Enrollment Status Records','2014-07-22 17:05:52');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newVisits','en','lava','crms',NULL,'importLog','newVisits',NULL,'c','numeric',NULL,'New Visits Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Visits Created','2014-07-22 17:06:52');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingVisits','en','lava','crms',NULL,'importLog','existingVisits',NULL,'c','numeric',NULL,'Already Existing Visits',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Visits','2014-07-22 17:08:22');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.newInstruments','en','lava','crms',NULL,'importLog','newInstruments',NULL,'c','numeric',NULL,'New Instruments Created',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'New Instruments Created','2014-07-22 17:09:37');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingInstruments','en','lava','crms',NULL,'importLog','existingInstruments',NULL,'c','numeric',NULL,'Already Exisitng Instruments',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Instruments','2014-07-22 17:11:00');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) VALUES('*.importLog.existingInstrumentsWithData','en','lava','crms',NULL,'importLog','existingInstrumentsWithData',NULL,'c','numeric',NULL,'Already Existing Instruments With Data',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Already Existing Instruments With Data','2014-07-22 17:14:34');

DELETE FROM versionhistory WHERE module='lava-crms-data' AND version='3.5.0';
INSERT INTO versionhistory(`Module`,`Version`,`VersionDate`,`Major`,`Minor`,`Fix`,`UpdateRequired`)
VALUES ('lava-crms-data','3.5.0','2014-08-21',3,5,0,0);

