/**
 * May 1, 2006
 *
 * Copyright 2004 uitags
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.sf.uitags.tag.panel;

import javax.servlet.jsp.JspException;

import net.sf.uitags.tag.AbstractUiTag;
import net.sf.uitags.tagutil.validation.RuntimeValidator;
import net.sf.uitags.util.Template;

/**
 * Injects a drag capability to a widget of a panel.
 *
 * @author hgani
 * @version $Id$
 */
public class DragTag extends AbstractUiTag {

  ///////////////////////////////
  ////////// Constants //////////
  ///////////////////////////////

  /**
   * Serial Version UID.
   */
  private static final long serialVersionUID = 100L;


  ////////////////////////////
  ////////// Fields //////////
  ////////////////////////////

  /**
   * The 'injectTo' tag attribute.
   */
  private String injectTo;

  /**
   * The 'injectToName' tag attribute.
   */
  private String injectToName;


  ///////////////////////////////////////////
  ////////// Tag attribute setters //////////
  ///////////////////////////////////////////

  /**
   * Tag attribute setter.
   *
   * @param val value of the tag attribute
   */
  public void setInjectTo(String val) {
    this.injectTo = val;
  }

  /**
   * Tag attribute setter.
   *
   * @param val value of the tag attribute
   */
  public void setInjectToName(String val) {
    this.injectToName = val;
  }


  ///////////////////////////////
  ////////// Tag logic //////////
  ///////////////////////////////

  /**
   * Instructs web container to skip the tag's body. 
   *
   * @see javax.servlet.jsp.tagext.Tag#doStartTag()
   * @return <code>SKIP_BODY</code>
   * @throws JspException to communicate error
   */
  public int doStartTag() throws JspException {
    return SKIP_BODY;
  }

  /**
   * Passes code generated by the child tag to its parent. 
   *
   * @see javax.servlet.jsp.tagext.Tag#doEndTag()
   * @return <code>EVAL_PAGE</code>
   * @throws JspException to communicate error
   */
  public int doEndTag() throws JspException {
    RuntimeValidator.assertAttributeExclusive(
        "injectTo", this.injectTo, "injectToName", this.injectToName);
    RuntimeValidator.assertEitherSpecified(
        "injectTo", this.injectTo, "injectToName", this.injectToName);

    PanelTag parent = (PanelTag) findParent(PanelTag.class);

    Template tpl = Template.forName(Template.PANEL_DRAG);
    tpl.map("draggerId", this.injectTo);
    tpl.map("draggerName", this.injectToName);
    parent.addChildJsCode(tpl.evalToString());

    return EVAL_PAGE;
  }
} 
