source 0_set_vars.sql

DELETE from datadictionary where instance=@instance and scope=@scope and entity=@entity;

INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','1','ftdppasl','1. Does the subject have an acquired and progressive difficulty with language consistent with PPA of a neurodegenerative type?','0 = No; 1 = Yes; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPASL','1','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','2','ftdppapo','2. Poor object naming','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPAPO','2','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','3','ftdppaiw','3. Impoverished word selection / retrieval in spontaneous speech or writing','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPAIW','3','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','4','ftdppasw','4. Impaired word comprehension','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPASW','4','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','5','ftdppapk','5. Poor object/person knowledge','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPAPK','5','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','6','ftdppags','6. Grammatical simplification or grammatical errors in speech or writing','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPAGS','6','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','7','ftdppaeh','7. Effortful, halting speech','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPAEH','7','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','8','ftdppacs','8. Circumlocutory, empty speech','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPACS','8','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','9','ftdppass','9. Speech sound/word errors (paraphasias)','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPASS','9','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','10','ftdppasr','10. Impaired speech repetition (inability to repeat verbatim sentence-length material)','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPASR','10','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','11','ftdppasd','11. Surface dyslexia and dysgraphia','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDPPASD','11','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','12','ftdcppa','12. ROOT DIAGNOSIS OF PPA','0 = No; 1 = Yes','','1','udsftldclinfeatures','FTDCPPA','12','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','13','ftdcppas','13. Consensus diagnosis of dominant PPA subtype based on clinician and neuropsychologist judgment','1 = PPA, semantic variant (semPPA); 2 = PPA, nonfluent/agrammatic variant (nf/gPPA); 3 = PPA, Logopenic variant; 4 = PPA not otherwise specified','','1','udsftldclinfeatures','FTDCPPAS','13','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','14','ftdbvcln','14. Does the subject have acquired, clinically important alterations in behavior, personality, or comportment consistent with bvFTD of a neurodegenerative type?','0 = No; 1 = Yes; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVCLN','14','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','15','ftdbvdis','15. Disinhibition','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVDIS','15','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','16','ftdbvapa','16. Apathy or inertia','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVAPA','16','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','17','ftdbvlos','17. Loss of sympathy / empathy','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVLOS','17','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','18','ftdbvrit','18. Ritualistic / compulsive behavior','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVRIT','18','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','19','ftdbvhyp','19. Hyperorality and appetite changes','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVHYP','19','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','20','ftdbvneu','20. Changes on neuropsychological testing consistent with bvFTD','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVNEU','20','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','21','ftdbvidl','21. Impaired daily functioning','0 = Absent; 1 = Questionably present; 2 = Definitely present; 9 = Not evaluated','','1','udsftldclinfeatures','FTDBVIDL','21','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','22','ftdbvft','22. Does the subject meet the criteria for clinical probable or possible bvFTD syndrome?','0 = Meets < 3 of the features described in Question 15-21.; 1 = Probable bvFTD; 2 = Meets criteria for possible bvFTD and has impaired daily functioning; 3 = Meets criteria for possible bvFTD but daily functioning is not impaired','','1','udsftldclinfeatures','FTDBVFT','22','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','23','ftdemgpv','23. Was an electromyogram (EMG) performed at this visit?','0 = No; 1 = Yes','','1','udsftldclinfeatures','FTDEMGPV','23','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','24','ftdemgpy','24. Has an EMG been performed in the past year?','0 = No; 1 = Yes','','1','udsftldclinfeatures','FTDEMGPY','24','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','25','ftdemgmn','25. If an EMG was performed, did it show evidence of motor neuron disease?','0 = No; 1 = Yes; 9 = Uncertain','','1','udsftldclinfeatures','FTDEMGMN','25','smallint','','1','null');
INSERT INTO datadictionary (`instance`,`scope`,`entity`,`prop_order`,`prop_name`,`prop_description`,`data_values`,`data_calculation`,`required`,`db_table`,`db_column`,`db_order`,`db_datatype`,`db_datalength`,`db_nullable`,`db_default`) VALUES ('lava','crms-nacc','udsftldclinfeatures2','26','ftdpabvf','26. In subjects with a diagnosis of PPA and bvFTD, which diagnosis appeared first?','1 = bvFTD; 2 = PPA, semantic variant; 3 = PPA, nonfluent/agrammatic variant; 4 = PPA, Logopenic variant; 5 = PPA not otherwise specified; 9 = Unknown','','1','udsftldclinfeatures','FTDPABVF','26','smallint','','1','null');

call util_createtable(@entity,@scope);
SELECT '';
call util_tablekeysadd(@entity,@scope);
SELECT '';
SELECT concat('INSERT IGNORE into instrument(instrname, tablename, formname, hasversion) values(\'', @instrname, '\',\'Multiple\',\'LavaWebOnly\',1);');