package net.sf.uitags.tag.calendar;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.jsp.JspException;

import net.sf.uitags.tag.AbstractUiTag;
import net.sf.uitags.util.Template;

public class CalendarTag extends AbstractUiTag {
  ///////////////////////////////
  ////////// Constants //////////
  ///////////////////////////////

  /**
   * Serial Version UID.
   */
  private static final long serialVersionUID = 100L;


  ////////////////////////////
  ////////// Fields //////////
  ////////////////////////////

  private CalendarGridTag calendarGrid;

  /**
   * List of code Strings generated by child tags, which is to be included
   * somewhere in the parent's generated code.
   */
  private List childJsCodeList;


  ///////////////////////////////
  ////////// Tag logic //////////
  ///////////////////////////////

  public int doStartTag() throws JspException {
    super.doStartTag();

    this.childJsCodeList = new ArrayList();

    makeVisibleToChildren();
    return EVAL_BODY_INCLUDE;
  }

  public int doEndTag() throws JspException {
    super.doEndTag();

    printJsCode();

    makeInvisibleFromChildren();
    return EVAL_PAGE;
  }

  private void printJsCode() throws JspException {
    Template tpl = Template.forName(Template.CALENDAR);

    String actionResolver = this.calendarGrid.getActionResolver();
    if (actionResolver == null) {
      actionResolver = "null";
    }

    tpl.map("gridId", this.calendarGrid.getId());
    tpl.map("gridClass", this.calendarGrid.getCssClass());
    tpl.map("weekLabels", this.calendarGrid.getWeekLabels());
    tpl.map("classResolver", this.calendarGrid.getClassResolver());
    tpl.map("otherAttributes", this.calendarGrid.getCustomHtmlAttributes());
    tpl.map("actionResolver", actionResolver);
    tpl.map("jsCodeList", this.childJsCodeList);

    println(tpl.evalToString());
  }


  /////////////////////////////////////////////////////
  ////////// To be used by nested child tags //////////
  /////////////////////////////////////////////////////

  void setCalendarGrid(CalendarGridTag calendarGrid) {
    this.calendarGrid = calendarGrid;
  }

  void addChildJsCode(String code) {
    this.childJsCodeList.add(code);
  }
}
