INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.patientOnlyImport','en','lava','crms',NULL,'importDefinition','patientOnlyImport',NULL,'i','toggle',NULL,'Only Import Patients',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Only Import Patients, not Visits or Instruments','2014-04-28 16:33:13');

INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.visitWindow','en','lava','crms',NULL,'importDefinition','visitWindow',NULL,'i','range',NULL,'Window around imported visit date to match existing Visit (+/- days)?',NULL,NULL,NULL,0,NULL,'importDefinition.visitWindow',NULL,NULL,'Window around imported visit date to match existing Visit (+/- days)?', '2014-11-12 16:33:13');

INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver','en','lava','crms',NULL,'importDefinition','instrCaregiver',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver2','en','lava','crms',NULL,'importDefinition','instrCaregiver2',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver3','en','lava','crms',NULL,'importDefinition','instrCaregiver3',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver4','en','lava','crms',NULL,'importDefinition','instrCaregiver4',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver5','en','lava','crms',NULL,'importDefinition','instrCaregiver5',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver6','en','lava','crms',NULL,'importDefinition','instrCaregiver6',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver7','en','lava','crms',NULL,'importDefinition','instrCaregiver7',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver8','en','lava','crms',NULL,'importDefinition','instrCaregiver8',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver9','en','lava','crms',NULL,'importDefinition','instrCaregiver9',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');
INSERT INTO viewproperty (`messageCode`,`locale`,`instance`,`scope`,`prefix`,`entity`,`property`,`section`,`context`,`style`,`required`,`label`,`label2`,`maxLength`,`size`,`indentLevel`,`attributes`,`list`,`listAttributes`,`propOrder`,`quickHelp`,`modified`) 
VALUES('*.importDefinition.instrCaregiver10','en','lava','crms',NULL,'importDefinition','instrCaregiver10',NULL,'i','toggle',NULL,'Caregiver instrument?',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'Is this instrument collected from a caregiver?', '2014-11-12 16:33:13');

DELETE FROM versionhistory WHERE module='lava-crms-data' AND version='3.5.1';
INSERT INTO versionhistory(`Module`,`Version`,`VersionDate`,`Major`,`Minor`,`Fix`,`UpdateRequired`)
VALUES ('lava-crms-data','3.5.1','2014-11-05',3,5,1,0);

